### PR TITLE
Arm commands

### PR DESCRIPTION
**Pull request by Shadowfacts1272**

### CODE REVIEW

**Comment by We1chJ** [comment]
@Stackfish5 This should be a Draft Pull Request. Can you please close this PR and make a Draft PR instead?

**Comment by prensing** [comment]
Stackfish: general comments:
there are way too many public variables and methods. Unless it is *actually* needed, variables and methods should be private. If variables are needed to be public (there should only be a few instances per class), you should create a "getter", eg "public double getX() {....}".

You have class "Arm" and class "ArmSubsystem" but both are Subsystems. It looks like "ArmSubsystem" is actually just the simulation, so you should rename it to something like "ArmSimulation" (no need for appending Subsystem, in most cases). 

We posted a week or so ago that constants which are only relevant to a single Subsystem (apart from CAN IDs) should be in the Subsystem itself (and private). 

The code does not actually compile for me. It seems to be missing items in Constants, and there is no Elevator subsystem.

**Comment by We1chJ** [comment]
@prensing This is just for the txt file in the command folder about the potential steps for a scoring command. It shows all the unfinished changes on Arm/Shoulder because this is based off from Zach's simulation branch. I will work on organizing these commands soon

**Comment by Shadowfacts1272** [comment]
Sorry about the inconvenience, it appears that I mistakenly committed the
arm simulation branch and the outline together. Sorry about that.

**Comment by prensing** [comment]
I closed this because it is subceded by the ArmReorg branch

**Pull request closed without merging**
