### PR TITLE
Auto follow trajectory

### PR DESCRIPTION
**Pull request by We1chJ**

### CODE REVIEW

**Comment by We1chJ** [comment]
It looks like the only way for me to transform the trajectory is to use the PathPlanner.generateTrajectory() method by passing in a list of transformed waypoints. We can't use the PathPlannerTrajectory() constructor as the normal transform method uses because the constructor method is private and some of the variables are private as well

**Comment by prensing** [comment]
Jack, for the end() and isFinished(), I think you should copy the code directly from ProxyCommand. 

Your reflectTraj function is not correct. You are missing that all rotations have to be negative. Again, you should copy the code from the PathPlanner methods except change the Y reflection to an X reflection.

Also, your editor is using TABs for indentation. Please make sure it is using 4 spaces.

**Comment by We1chJ** [comment]
Sorry I probably didn't make this clear and I should've commented in the code:

I did try to copy the whole thing in the transformStateForAlliance(). However, it won't work because 1) variable curveRadius and dealtaPos for a PathPlannerState object is private, so they can't be tranformed outside of the class (their library). 2) the original transformTrajectoryForAlliance at the end will pass the list of transformed states into the PathPlannerTrajectory constructor, which again is private and can't be accessed outside the library. 

So my approach is to use the PathPlanner.generatePath() function by passing in the transformed waypoints, and only transforming the translation, rotation, and holomonicRotation.

**Review by prensing — APPROVED** [review]
Looks good, but we should test it before checking in. Probably can't test red vs blue right away though.

**Pull request merged**
